2019-06-15 13:24:19,895 ERROR: Exception on /user/peace [GET] [in /home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/app/routes.py", line 86, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/app/templates/user.html", line 16, in block "content"
    <!-- <p><a href="{{ url_for('edit_profile') }}">Edit your profile</a></p> -->
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 2080, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/werkzeug/routing.py", line 2007, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit_profile'. Did you forget to specify values ['username']?
2019-06-15 13:24:34,598 INFO: Microblog startup [in /home/uferepeace/Documents/projects/FlaskMicroBlog/app/__init__.py:46]
2019-06-15 13:24:49,542 ERROR: Exception on /peace/edit_profile [GET] [in /home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/app/routes.py", line 91, in edit_profile
    form = EditProfileForm()
  File "/home/uferepeace/Documents/projects/FlaskMicroBlog/microblogvenv/lib/python3.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2019-06-15 13:26:59,255 INFO: Microblog startup [in /home/uferepeace/Documents/projects/FlaskMicroBlog/app/__init__.py:46]
2019-06-15 13:56:41,926 INFO: Microblog startup [in /home/uferepeace/Documents/projects/FlaskMicroBlog/app/__init__.py:46]
2019-06-15 13:57:32,217 INFO: Microblog startup [in /home/uferepeace/Documents/projects/FlaskMicroBlog/app/__init__.py:46]
2019-06-16 22:39:13,930 INFO: Microblog startup [in /home/uferepeace/Documents/projects/FlaskMicroBlog/app/__init__.py:46]
2019-06-16 22:40:28,673 INFO: Microblog startup [in /home/uferepeace/Documents/projects/FlaskMicroBlog/app/__init__.py:46]
2019-06-16 22:41:11,327 INFO: Microblog startup [in /home/uferepeace/Documents/projects/FlaskMicroBlog/app/__init__.py:46]
2019-06-16 23:13:07,768 INFO: Microblog startup [in /home/uferepeace/Documents/projects/FlaskMicroBlog/app/__init__.py:46]
2019-06-16 23:53:23,136 INFO: Microblog startup [in /home/uferepeace/Documents/projects/FlaskMicroBlog/app/__init__.py:46]
